# Generated by Django 2.2.3 on 2024-03-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
